### ISSUE TITLE
Crash at startup, conflict with Thaumcraft

### ISSUE THREAD

**Issue by goldenvixen** [Shinoow/AbyssalCraft-Integration#42]
#### Intro:

Game crashes at start up when loading mods.

#### Description:

Idk which update of Abyssalcraft borked this, but I do know the lasted version of Abyssalcraft combined with the integration mod and Thaumcraft causes crashes at mod load up. Plays just fine without the integration mod.

#### Crash report:

---- Minecraft Crash Report ----
// There are four lights!

Time: 2021-01-13 12:54:36 PST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumcraft (thaumcraft)
Caused by: java.lang.NoSuchFieldError: stone
    at com.shinoow.acintegration.integrations.thaumcraft.ACTCEvents.registerAspects(ACTCEvents.java:127)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2830_ACTCEvents_registerAspects_AspectRegistryEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at thaumcraft.common.config.ConfigAspects.postInit(ConfigAspects.java:45)
    at thaumcraft.proxies.CommonProxy.postInit(CommonProxy.java:82)
    at thaumcraft.proxies.ClientProxy.postInit(ClientProxy.java:54)
    at thaumcraft.Thaumcraft.postInit(Thaumcraft.java:54)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 1.12.2-forge-14.23.5.2855
- AbyssalCraft Integration: AbyssalCraft+Integration-1.12.2-1.11.2
- AbyssalCraft: AbyssalCraft-1.12.2-2.0.0-ALPHA-1

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by Shinoow** [comment]
AbyssalCraft Integration isn't compatible with AbyssalCraft 2.0.0-ALPHA-1 (well, at least not the Thaumcraft integration, I haven't checked any of the others either). Until AbyssalCraft leaves alpha there won't be any updates fixing this.

**Comment by DarianLStephens** [comment]
It appears to have left alpha at this point, now being in Beta, but Integration hasn't been updated.
Are there plans to, or is it not needed now, or what's up?

**Comment by Shinoow** [comment]
Oh, updating Integrations has been on the back-burner. At this point all notable API changes have been done, so it's just a matter of... well... mainly expanding the CraftTweaker integration, but also addressing this.
